services:
  bazaar:
    build:
      context: .
    container_name: bazaar
    volumes:
      - ./trades.db:/app/trades.db
      - ./app.log:/app/app.log
      - ./error.log:/app/error.log
    restart: always
    networks:
      - caddy
networks:
  caddy:
    external: true
